In [1]:
import numpy as np

In [2]:
x=([1,2,3],[2,4,6],[5,4,9])

# mean

In [3]:
x_mean=np.mean(x)

In [4]:
print(x_mean)

4.0


# Median

In [5]:
x_median=np.median(x)
print(x_median)

4.0


# standard daviation


In [6]:
x_s_d=np.std(x)
print(x_s_d)

2.309401076758503


# ***

In [12]:
print(x)

([1, 2, 3], [2, 4, 6], [5, 4, 9])


In [19]:
print(np.shape(x))

(3, 3)


In [8]:
print(np.mean(x,axis=0))

[2.66666667 3.33333333 6.        ]


In [9]:
print(np.mean(x,axis=1))

[2. 4. 6.]


In [10]:
print(np.median(x,axis=0))

[2. 4. 6.]


In [11]:
print(np.median(x,axis=1))

[2. 4. 5.]


In [20]:
print(np.size(x))

9
