## Genrate an random number array find mean median and standard daviation

In [1]:
import numpy as np

In [3]:
x=np.random.randint(1,100,(3,3))
print(x)

[[21 15 26]
 [63 61 53]
 [15 31 28]]


In [5]:
mean_x=np.mean(x)
print(mean_x)

34.77777777777778


In [6]:
median_x=np.median(x)
print(median_x)

28.0


In [7]:
STD_x=np.std(x)
print(STD_x)

18.029468333677
